let SERVER_HOST_CUSTOMER_API = "http://0.0.0.0:12001"

var development = {
	env : global.process.env.NODE_ENV || 'development',
	httpPort : process.env.PORT || 8080,
	httpHost : '0.0.0.0',
	portWebsocket : 4000,
	URL_PAYMENT_REQUEST_LIST: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	HEADER_AUTHORIZATION_TEST:"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqIjoiNjkzNTYxOTk1NTgiLCJuYW1lIjoiRVVDTElERVMgTk9HVUVJUkEgUk9EUklHVUVTIFRBVkFSRVMiLCJwaG9uZXMiOlsiKzU1NjE5OTk2MDUxNTEiXSwiYWNjb3VudHMiOlt7ImJyYW5jaC1udW1iZXIiOiIxIiwiYWNjb3VudC1udW1iZXIiOiIyNyJ9XSwidG9rZW4iOiJUR1QtMTEyMS1JYXNmVVhWdXlaMXdjZXlYQ09mYk5DQ2V2ZERRMEVubXhZNDZPdTZnTUZtT2daY05UMS1jZW50cmFsLWRlLWF1dGVudGljYWNhby1zaWNvb2ItY2FzLXNlZ3VyYW5jYS1zcHJpbmdib290LTEiLCJleHAiOjE1MjcwMDI1MTc2MzEsImlhdCI6MTUyNzAwMjUxNn0.XVvIoS499Gi9HyTqwVMNOzr8Ukbb64lb9MH9DBT9axNFS9S-5x9VtY70dRumlNshcYAK1gXwKuj09FBZUawwiA6SdLLt_1JmP8RqMxMSpcOwHmRELWlkqEgVMgre9-m-n3Xzi8fICc1SrB2PQ_burz9LR_hJzxnGJte9PD3i8p1hEvE-2b5THaa-h2rD0smX4PFTdQssvw_OFwfGUA7DTG2-QfQLcAnXZ3XnIkXp-HlBWQJCeT4wB8xDsy8MLU1qDBz4Z62D08M8G0goZtUn02P6VD-cCTnyl-smX7un727vPCnEw3galcaJG9e48MQe4loTIbni8I17bTrMKHm2nw",
	URL_PAYMENT_REQUEST_DETAIL: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_ADD: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_TOKEN: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_UPDATE: SERVER_HOST_CUSTOMER_API + "/payment-requests",
};


var production = {
	env : global.process.env.NODE_ENV || 'development',
	httpPort : process.env.PORT || 8080,
	httpHost : '0.0.0.0',
	portWebsocket : 4000,
	URL_PAYMENT_REQUEST_LIST: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	HEADER_AUTHORIZATION_TEST:"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqIjoiNjkzNTYxOTk1NTgiLCJuYW1lIjoiRVVDTElERVMgTk9HVUVJUkEgUk9EUklHVUVTIFRBVkFSRVMiLCJwaG9uZXMiOlsiKzU1NjE5OTk2MDUxNTEiXSwiYWNjb3VudHMiOlt7ImJyYW5jaC1udW1iZXIiOiIxIiwiYWNjb3VudC1udW1iZXIiOiIyNyJ9XSwidG9rZW4iOiJUR1QtMTEyMS1JYXNmVVhWdXlaMXdjZXlYQ09mYk5DQ2V2ZERRMEVubXhZNDZPdTZnTUZtT2daY05UMS1jZW50cmFsLWRlLWF1dGVudGljYWNhby1zaWNvb2ItY2FzLXNlZ3VyYW5jYS1zcHJpbmdib290LTEiLCJleHAiOjE1MjcwMDI1MTc2MzEsImlhdCI6MTUyNzAwMjUxNn0.XVvIoS499Gi9HyTqwVMNOzr8Ukbb64lb9MH9DBT9axNFS9S-5x9VtY70dRumlNshcYAK1gXwKuj09FBZUawwiA6SdLLt_1JmP8RqMxMSpcOwHmRELWlkqEgVMgre9-m-n3Xzi8fICc1SrB2PQ_burz9LR_hJzxnGJte9PD3i8p1hEvE-2b5THaa-h2rD0smX4PFTdQssvw_OFwfGUA7DTG2-QfQLcAnXZ3XnIkXp-HlBWQJCeT4wB8xDsy8MLU1qDBz4Z62D08M8G0goZtUn02P6VD-cCTnyl-smX7un727vPCnEw3galcaJG9e48MQe4loTIbni8I17bTrMKHm2nw",
	URL_PAYMENT_REQUEST_DETAIL: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_ADD: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_TOKEN: SERVER_HOST_CUSTOMER_API + "/payment-requests",
	URL_PAYMENT_REQUEST_UPDATE: SERVER_HOST_CUSTOMER_API + "/payment-requests",
};

exports.Config = global.process.env.NODE_ENV === 'production' ? production : development;
